In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('https://bit.ly/perch_csv_data')
perch_full = df.to_numpy()
print(perch_full)

[[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]
 [16.2   4.59  2.63]
 [17.4   4.59  2.94]
 [18.    5.22  3.32]
 [18.7   5.2   3.12]
 [19.    5.64  3.05]
 [19.6   5.14  3.04]
 [20.    5.08  2.77]
 [21.    5.69  3.56]
 [21.    5.92  3.31]
 [21.    5.69  3.67]
 [21.3   6.38  3.53]
 [22.    6.11  3.41]
 [22.    5.64  3.52]
 [22.    6.11  3.52]
 [22.    5.88  3.52]
 [22.    5.52  4.  ]
 [22.5   5.86  3.62]
 [22.5   6.79  3.62]
 [22.7   5.95  3.63]
 [23.    5.22  3.63]
 [23.5   6.28  3.72]
 [24.    7.29  3.72]
 [24.    6.38  3.82]
 [24.6   6.73  4.17]
 [25.    6.44  3.68]
 [25.6   6.56  4.24]
 [26.5   7.17  4.14]
 [27.3   8.32  5.14]
 [27.5   7.17  4.34]
 [27.5   7.05  4.34]
 [27.5   7.28  4.57]
 [28.    7.82  4.2 ]
 [28.7   7.59  4.64]
 [30.    7.62  4.77]
 [32.8  10.03  6.02]
 [34.5  10.26  6.39]
 [35.   11.49  7.8 ]
 [36.5  10.88  6.86]
 [36.   10.61  6.74]
 [37.   10.84  6.26]
 [37.   10.57  6.37]
 [39.   11.14  7.49]
 [39.   11.14  6.  ]
 [39.   12.43  7.35]
 [40.   11.93

In [5]:
import numpy as np

perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

In [6]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(perch_full, perch_weight, random_state=42)

In [7]:
# 변환기 클래스, fit, transform 메서드 제공
from sklearn.preprocessing import PolynomialFeatures

In [8]:
# degree = 2 기본값
poly = PolynomialFeatures()
# 두개의 특성 2,3으로 이루어진 샘플을 조합함
poly.fit([[2, 3]])
# transform: 특성을 반환하는 함수
print(poly.transform([[2, 3]]))

[[1. 2. 3. 4. 6. 9.]]


무게 = a * 길이 + b * 높이 + c * 두께 + d * 1           
      
이렇게 놓고 보면 특성은 (길이, 높이, 두께, 1)이 됩니다    

절편을 위한 특성을 자동으로 추가해줌 
      


In [9]:
# 절편을 위한 항을 제거하고 특성의 제곱과 특성끼리 곱한 항만 추가
poly = PolynomialFeatures(include_bias=False)
poly.fit(([[2,3]]))
print(poly.transform([[2,3]]))

[[2. 3. 4. 6. 9.]]


In [10]:
poly = PolynomialFeatures(include_bias=False)
# train_input 특성의 샘플을 조합
poly.fit(train_input)
# 특성 반환
train_poly = poly.transform(train_input)
# 9개의 특성을 가짐
print(train_poly.shape)

(42, 9)


In [11]:
# 9개의 특성이 각가 어떤 입력의 조합으로 만들어졌는지 확인
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [12]:
# 테스트셋 반환
test_poly = poly.transform(test_input)

### 다중 회귀 모델 훈련하기

- 다중 회귀 모델을 훈련하는 것은 선형 회귀 모델을 훈련하는 것과 같다.         
- 다만, 여러개의 특성을 사용하여 선형회귀를 수행하는 것뿐이다.      
- 앞장에서 사용한 LinearRegrssion 클래스를 사용



In [13]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(train_poly, train_target)
print("트레인셋:",lr.score(train_poly, train_target))
print("테스트셋:",lr.score(test_poly, test_target))

트레인셋: 0.9903183436982124
테스트셋: 0.9714559911594203


In [14]:
# dgree = 5
poly = PolynomialFeatures(degree=5, include_bias=False)

# train_input 특성의 샘플을 조합
poly.fit(train_input)

# 특성 반환
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)

# 55개의 특성 확인
print(train_poly.shape)

(42, 55)


In [16]:
lr.fit(train_poly, train_target)
print('트레이셋:', lr.score(train_poly, train_target))
print('테스트셋:', lr.score(test_poly, test_target))

트레이셋: 0.999999999997515
테스트셋: -144.40196592191958


### 결과      
- 특성의 개수를 크게 늘리면 선형 모델은 복잡해진다.           
- 훈련 세트에 대해 거의 완벽하게 학습함           
- 훈련 세트에 대해 과적합      

### 규제
- 훈련세트를 너무 과도하게 학습하지 못하도록 훼방하는 것을 말함         
- 즉 모델이 과대적합되지 않도록 만드는 것이다.   

### 방법
- 정규화: 특성에 곱해지는 계수의 크기를 작게 만든다.       

https://rk1993.tistory.com/entry/Ridge-regression%EC%99%80-Lasso-regression-%EC%89%BD%EA%B2%8C-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0

In [20]:
# 정규화 클래스
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
# 특성의 샘플을 조합
ss.fit(train_poly)

# 정규화를 거친 특성을 반환
train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

print(train_scaled.shape)

(42, 55)


In [24]:
# 릿지회귀
from sklearn.linear_model import Ridge

ridge = Ridge()
ridge.fit(train_scaled, train_target)
print('트레인셋:', ridge.score(train_scaled, train_target))
print('테스트셋:', ridge.score(test_scaled, test_target))

트레인셋: 0.9896101671037343
테스트셋: 0.9790693977615393
